/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Billboard, Text } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/ballscrog.glb");
	return (
		<group {...props} dispose={null}>
			<group scale={[1, 1, 3.815]}>
				{" "}
				position={[-5, 0, -5]}
				<mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials["Material.009"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials["Material.001"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={materials["Material.002"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_3.geometry} material={materials["Material.003"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_4.geometry} material={materials["Material.005"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_5.geometry} material={materials["Material.007"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_6.geometry} material={materials["Material.006"]} />
				<mesh castShadow receiveShadow geometry={nodes.Cube002_7.geometry} material={materials["Material.008"]} />
			</group>
		</group>
	);
}

useGLTF.preload("/ballscrog.glb");
